namespace NodeJS {
  interface ProcessEnv {
    /**
     * The URL to access the Edge Config for the project.
     */
    readonly EDGE_CONFIG: string
    /**
     * @ignore
     */
    readonly VERCEL: '1'
    /**
     * The Vercel environment that the project is deployed to. It is automatically set by Vercel at build time in the
     * pipeline.
     */
    readonly VERCEL_ENV: 'production' | 'preview' | 'development'
    /**
     * @ignore
     */
    readonly VERCEL_GIT_COMMIT_AUTHOR_LOGIN: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_COMMIT_AUTHOR_NAME: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_COMMIT_MESSAGE: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_COMMIT_REF: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_COMMIT_SHA: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_PREVIOUS_SHA: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_PROVIDER: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_PULL_REQUEST_ID: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_REPO_ID: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_REPO_OWNER: string
    /**
     * @ignore
     */
    readonly VERCEL_GIT_REPO_SLUG: string
    /**
     * @ignore
     */
    readonly VERCEL_URL: string
    /**
     * The URL of the Clerk project that the project uses for the sign up page.
     */
    readonly NEXT_PUBLIC_CLERK_SIGN_UP_URL: string
    /**
     * The URL of the Clerk project that the project uses for the sign in page.
     */
    readonly NEXT_PUBLIC_CLERK_SIGN_IN_URL: string
    /**
     * The URL of the Clerk project after the user signs up.
     */
    readonly NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: string
    /**
     * The URL of the Clerk project after the user signs in.
     */
    readonly NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: string
    /**
     * The Clerk secret key.
     */
    readonly CLERK_SECRET_KEY: string
    /**
     * The public key of the Clerk project that the project uses for authentication.
     */
    readonly NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string
    /**
     * The PRIVATE key of the Clerk project that the project uses for authentication.
     */
    readonly CLERK_SECRET_KEY: string
    /**
     * The URL of the PostgreSQL database for the project.
     */
    readonly POSTGRES_URL: string
    /**
     * The URL of the PostgreSQL database for the project that is used by the Prisma ORM.
     */
    readonly POSTGRES_PRISMA_URL: string
    /**
     * The non-pooling URL of the PostgreSQL database for the project.
     */
    readonly POSTGRES_URL_NON_POOLING: string
    /**
     * The username of the PostgreSQL database for the project.
     */
    readonly POSTGRES_USER: string
    /**
     * The host of the PostgreSQL database for the project.
     */
    readonly POSTGRES_HOST: string
    /**
     * The password of the PostgreSQL database for the project.
     */
    readonly POSTGRES_PASSWORD: string
    /**
     * The database name of the PostgreSQL database for the project.
     */
    readonly POSTGRES_DATABASE: string
    /**
     * The Firebase Client SDK API key for the project.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     */
    readonly FIREBASE_CLIENT_API_KEY: string
    /**
     * The Firebase Client SDK authentication domain for the project, e.g. `party-planner-{{projectID}}.firebaseapp.com`
     * that is generated by Firebase.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     *
     * @example "party-planner-123a4.firebaseapp.com"
     */
    readonly FIREBASE_CLIENT_AUTH_DOMAIN: string
    /**
     * The Firebase Client SDK database URL for the project, e.g.
     * `https://{{projectID}}-{{defaultCollection}}-rtdb.firebaseio.com`.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     *
     * @example "https://party-planner-123a4-default-rtdb.firebaseio.com"
     */
    readonly FIREBASE_CLIENT_DATABASE_URL: string
    /**
     * The Firebase Client SDK project ID for the project. Commonly the same as the {@link FIREBASE_ADMIN_PROJECT_ID}
     * environment variable.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     * @see {@link FIREBASE_ADMIN_PROJECT_ID}
     *
     * @example "party-planner-123a4"
     */
    readonly FIREBASE_CLIENT_PROJECT_ID: string
    /**
     * The Firebase Client SDK storage bucket for the project, e.g. `{{projectID}}.appspot.com`.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     *
     * @example "party-planner-123a4.appspot.com"
     */
    readonly FIREBASE_CLIENT_STORAGE_BUCKET: string
    /**
     * The Firebase Client SDK messaging sender ID for the project.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     */
    readonly FIREBASE_CLIENT_MESSAGING_SENDER_ID: string
    /**
     * The Firebase Client SDK app ID for the project.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     */
    readonly FIREBASE_CLIENT_APP_ID: string
    /**
     * The Firebase Client SDK measurement ID for the project.
     *
     * @see https://firebase.google.com/docs/web/setup#add-sdks-initialize
     */
    readonly FIREBASE_CLIENT_MEASUREMENT_ID: string
    /**
     * The [NextJS](https://nextjs.org) environment variable that contains the URL of the Vercel deployment for the
     * project. It is automatically set by Vercel at build time in the pipeline.
     *
     * This variable shall not have the HTTP/HTTPS protocol (i.e. `http://` or `https://`) prefix on the development
     * environment because Vercel does not inject the protocol at build time into this variable.
     *
     * @see https://vercel.com/docs/environment-variables#system-environment-variables
     *
     * @example "localhost:3000"
     * @example "party-planner.mrlemoos.dev"
     */
    readonly NEXT_PUBLIC_VERCEL_URL: string
    /**
     * The URL of the Firebase Realtime Database for the project.
     *
     * @see https://firebase.google.com/docs/database
     */
    readonly FIREBASE_ADMIN_REALTIME_DATABASE_URL: string
    /**
     * The type of the credentials for the Firebase Admin SDK (i.e. `firebase-admin` module on npm registry.) It always
     * has the value of `service_account`.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     * @see https://www.npmjs.com/package/firebase-admin
     */
    readonly FIREBASE_ADMIN_CREDENTIAL_TYPE: 'service_account'
    /**
     * The ID of the Firebase project that the Firebase Admin SDK will be used for.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_PROJECT_ID: string
    /**
     * The ID of the private key that the Firebase Admin SDK will use to authenticate with the Firebase services.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_PRIVATE_KEY_ID: string
    /**
     * The private key that the Firebase Admin SDK will use to authenticate with the Firebase services.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_PRIVATE_KEY: string
    /**
     * The email address of the Firebase Admin SDK client.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_CLIENT_EMAIL: string
    /**
     * The ID of the Firebase Admin SDK client.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_CLIENT_ID: string
    /**
     * The URL of the Firebase Admin SDK authentication service.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_AUTH_URI: string
    /**
     * The URL of the Firebase Admin SDK token service.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_TOKEN_URI: string
    /**
     * The URL of the Firebase Admin SDK authentication provider.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL: string
    /**
     * The URL of the Firebase Admin SDK client certificate.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_CLIENT_X509_CERT_URL: string
    /**
     * The domain of the Firebase Admin SDK universe.
     *
     * @see https://firebase.google.com/docs/admin/setup#initialize-sdk
     */
    readonly FIREBASE_ADMIN_UNIVERSE_DOMAIN: string
  }
}
